[server]
host=127.0.0.1
port=8080
threadnums=4
isET=false
isDaemonize=false
[log]
isAsync=false 
logLevel=debug
logPath=../Log.log
modules=SYSTEM
    SIGNAL
    TIME
    EVENT
    TCP
[AsyncLog]
BufferSize=20

