[server]
host=0.0.0.0
port=8080
threadnums=4
[log]
isAsync=false 
logLevel=debug
logPath=../Log.log
modules=SYSTEM
    SIGNAL
    TIME
    EVENT
    TCP
[AsyncLog]
flush_interval=10s
BufferSize=20
[SyncLog]
flush_interval=10ms
